// swift-tools-version: 6.2

// © 2025–2026 John Gary Pusey (see LICENSE.md)

import PackageDescription

let swiftSettings: [SwiftSetting] = [.defaultIsolation(nil),
                                     .enableUpcomingFeature("ExistentialAny"),
                                     .enableUpcomingFeature("ImmutableWeakCaptures"),
                                     .enableUpcomingFeature("InferIsolatedConformances"),
                                     .enableUpcomingFeature("InternalImportsByDefault"),
                                     .enableUpcomingFeature("MemberImportVisibility"),
                                     .enableUpcomingFeature("NonisolatedNonsendingByDefault")]

let package = Package(name: "IvorModel",
                      platforms: [.iOS(.v18),
                                  .macOS(.v15)],
                      products: [.library(name: "IvorModel",
                                          targets: ["IvorModel"])],
                      dependencies: [.package(url: "https://github.com/eBardX/IvorTiming.git",
                                              .upToNextMajor(from: "0.2.0")),
                                     .package(url: "https://github.com/eBardX/IvorTuning.git",
                                              .upToNextMajor(from: "0.5.0")),
                                     .package(url: "https://github.com/eBardX/XestiMarkov.git",
                                              .upToNextMajor(from: "3.0.0")),
                                     .package(url: "https://github.com/eBardX/XestiNumbers.git",
                                              .upToNextMajor(from: "1.0.0")),
                                     .package(url: "https://github.com/eBardX/XestiSexp.git",
                                              .upToNextMajor(from: "4.1.0")),
                                     .package(url: "https://github.com/eBardX/XestiTools.git",
                                              .upToNextMajor(from: "7.4.0"))],
                      targets: [.target(name: "IvorModel",
                                        dependencies: [.product(name: "IvorTiming",
                                                                package: "IvorTiming"),
                                                       .product(name: "IvorTuning",
                                                                package: "IvorTuning"),
                                                       .product(name: "XestiMarkov",
                                                                package: "XestiMarkov"),
                                                       .product(name: "XestiNumbers",
                                                                package: "XestiNumbers"),
                                                       .product(name: "XestiSexp",
                                                                package: "XestiSexp"),
                                                       .product(name: "XestiTools",
                                                                package: "XestiTools")],
                                        swiftSettings: swiftSettings),
                                .testTarget(name: "IvorModelTests",
                                            dependencies: [.target(name: "IvorModel"),
                                                           .product(name: "IvorTiming",
                                                                    package: "IvorTiming"),
                                                           .product(name: "IvorTuning",
                                                                    package: "IvorTuning"),
                                                           .product(name: "XestiMarkov",
                                                                    package: "XestiMarkov"),
                                                           .product(name: "XestiNumbers",
                                                                    package: "XestiNumbers")],
                                            swiftSettings: swiftSettings)],
                      swiftLanguageModes: [.v6])
